Repository codingBear01/cosmost_fe, pull requests merged in 2022-10, with the labels that each got.

#1 회원가입 유효성 검사 출력 수정
  src/components/ui/SignUpForm/SignUpForm.jsx
Labels: enhancement

#15 Done: 코스 검색 결과 페이지 레이아웃 완성
  src/App.js
  src/components/index.js
  src/components/pages/CourseDetail.jsx
  src/components/pages/SearchedCourses.jsx
  src/components/pages/index.js
  src/components/ui/CourseDetailForm/CourseContent/styled.js
  src/components/ui/CourseDetailForm/CourseContentWrap/styled.js
  src/components/ui/SearchedCoursesForm/SearchedCourse/SearchedCourse.jsx
  src/components/ui/SearchedCoursesForm/SearchedCourse/index.js
  src/components/ui/SearchedCoursesForm/SearchedCourse/styled.js
  src/components/ui/SearchedCoursesForm/SearchedCoursesForm.jsx
  src/components/ui/SearchedCoursesForm/SelectingCategoryArea/SelectingCategoryArea.jsx
  src/components/ui/SearchedCoursesForm/SelectingCategoryArea/index.js
  src/components/ui/SearchedCoursesForm/SelectingCategoryArea/styled.js
  src/components/ui/SearchedCoursesForm/index.js
  src/components/ui/SearchedCoursesForm/styled.js
  src/components/ui/index.js
  src/store/index.js
  src/store/temporaryArray/Courses.js
  src/store/temporaryArray/index.js
Labels: enhancement

#20 Done: 코스 url sns 공유, 모달 디자인 및 관련 기능, 회원가입 유효성 검증 메시지 스타일 수정 등
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/common/CourseUtillityModal/CourseUtillityModal.jsx
  src/components/common/CourseUtillityModal/index.js
  src/components/common/CourseUtillityModal/styled.js
  src/components/common/FlexDiv/FlexDiv.jsx
  src/components/common/FlexDiv/index.js
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderSearchBar/HeaderSearchBar.jsx
  src/components/common/HistoriesForm/HistoriesForm.jsx
  src/components/common/HistoriesForm/index.js
  src/components/common/HistoriesForm/styled.js
  src/components/common/OrderingModal/OrderingModal.jsx
  src/components/common/ReportForm/ReportForm.jsx
  src/components/common/ReportForm/index.js
  src/components/common/ReportForm/styled.js
  src/components/common/ToTopBtn/ToTopBtn.jsx
  src/components/common/ToTopBtn/styled.js
  src/components/common/UtilInputWrap/UtilInputWrap.jsx
  src/components/common/UtilInputWrap/styled.js
  src/components/common/index.js
  src/components/index.js
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseContentWrap/styled.js
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseReview/styled.js
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/index.js
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/styled.js
  src/components/ui/CourseDetailForm/CourseSharingModal/CourseSharingModal.jsx
  src/components/ui/CourseDetailForm/CourseSharingModal/index.js
  src/components/ui/CourseDetailForm/CourseSharingModal/styled.js
  src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/index.js
  src/components/ui/CourseDetailForm/CourseTitleAndDate/styled.js
  src/components/ui/CourseDetailForm/index.js
  src/components/ui/DaumAddressApiForm/DaumAddressApiForm.jsx
  src/components/ui/EmailValidationForm/EmailValidationForm.jsx
  src/components/ui/FollowsForm/FollowsForm.jsx
  src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/MainSection/MainCourse/MainCourse.jsx
  src/components/ui/MainSection/MainSection.jsx
  src/components/ui/SearchedCoursesForm/SearchedCoursesForm.jsx
  src/components/ui/SignUpForm/SignUpForm.jsx
  src/components/ui/SignUpForm/styled.js
  src/components/ui/UserPageForm/UserPageMenuList/UserPageMenuList.jsx
  src/components/ui/UserPageForm/UserProfilArea/UserProfilArea.jsx
  src/components/ui/index.js
  src/index.css
  src/index.js
  src/store/index.js
  src/store/recoilStates.js
  src/store/sharing.js
  src/store/temporaryArray/MainCourses.js
Labels: enhancement

#22 #4 [create] 코스 이미지 드래그 앤 드랍 기능 추가
  package-lock.json
  package.json
  src/App.js
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/CourseRegistrationForm/styled.js
  src/components/ui/LoginForm/LoginForm.jsx
  src/index.js
Labels: enhancement

#23 Done: 코스 등록, 수정, 삭제/Merge with PR #22
  package-lock.json
  package.json
  public/index.html
  src/components/common/CourseUtillityModal/CourseUtillityModal.jsx
  src/components/hooks/index.js
  src/components/hooks/useInterval.js
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseReview/styled.js
  src/components/ui/CourseDetailForm/CourseReviewRegisterForm/CourseReviewRegisterForm.jsx
  src/components/ui/CourseDetailForm/CourseReviewRegisterForm/styled.js
  src/components/ui/CourseDetailForm/CourseSharingModal/CourseSharingModal.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/store/temporaryArray/CourseReviews.js
  src/style/styles.js
Labels: enhancement

#24 #4 [update] 코스 이미지 드래그 앤 드랍 버그 수정
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
Labels: bug

#27 Done: 삭제 확인 모달 구현, 코스 리뷰 get, delete api 구현
  src/components/common/CourseUtillityModal/CourseUtillityModal.jsx
  src/components/common/DeleteModal/DeleteModal.jsx
  src/components/common/DeleteModal/index.js
  src/components/common/DeleteModal/styled.js
  src/components/common/HistoriesForm/HistoriesForm.jsx
  src/components/common/HistoriesForm/styled.js
  src/components/common/index.js
  src/components/index.js
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseReview/styled.js
  src/components/ui/CourseDetailForm/CourseReviewRegisterForm/CourseReviewRegisterForm.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/SignUpForm/SignUpForm.jsx
  src/store/index.js
  src/store/temporaryArray/ReviewHistories.js
  src/store/temporaryArray/index.js
Labels: 🦾enhancement

#31 #4 코스등록 페이지 모든 API 기능 구현
  package.json
  src/components/common/Icon/Icon.jsx
  src/components/common/Icon/styled.js
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/CourseRegistrationForm/styled.js
Labels: 🦾enhancement

#34 #7 [update] 프로파일 이미지 바이너리 데이터로 변환 가능하도록 수정
  src/App.js
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/SearchedCoursesForm/SearchedCoursesForm.jsx
  src/components/ui/SignUpForm/SignUpForm.jsx
  src/store/function.js
  src/store/index.js
Labels: 🦾enhancement

#37 코스 상세페이지 대부분의 API 구현
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseImageCarousel/CourseImageCarousel.jsx
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/store/function.js
  src/store/index.js
Labels: 🦾enhancement

#38 Done: 이메일 인증 및 회원가입 페이지 닉네임 중복확인 기능 등 구현
  src/App.js
  src/components/common/DeleteModal/DeleteModal.jsx
  src/components/common/HistoriesForm/HistoriesForm.jsx
  src/components/common/MenuListForm/MenuListForm.jsx
  src/components/common/MenuListForm/index.js
  src/components/common/MenuListForm/styled.js
  src/components/common/OrderingModal/OrderingModal.jsx
  src/components/common/PageContainer/PageContainer.jsx
  src/components/common/PageContainer/styled.js
  src/components/common/ReportForm/ReportForm.jsx
  src/components/common/index.js
  src/components/index.js
  src/components/pages/ErrorPage.jsx
  src/components/pages/Follows.jsx
  src/components/pages/Histories.jsx
  src/components/pages/InputAddress.jsx
  src/components/pages/NotFoundPage.jsx
  src/components/pages/Ranking.jsx
  src/components/pages/index.js
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseReviewRegisterForm/CourseReviewRegisterForm.jsx
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/CourseRegistrationForm/styled.js
  src/components/ui/DaumAddressApiForm/styled.js
  src/components/ui/EmailValidationForm/EmailValidationForm.jsx
  src/components/ui/InputAddressForm/InputAddressForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/SignUpForm/SignUpForm.jsx
  src/components/ui/UserPageForm/UserPageForm.jsx
  src/components/ui/UserPageForm/UserPageMenuList/index.js
  src/components/ui/UserPageForm/UserProfilArea/UserProfilArea.jsx
  src/components/ui/UserPageForm/index.js
  src/store/index.js
  src/store/recoilStates.js
Labels: 🦾enhancement

#40 #3, #7 [update] 코스 수정 API 및 코스 삭제 API 구현 완료, 회원가입 API 이미지 업로드 구현 완료
  src/App.js
  src/components/common/CourseUtillityModal/CourseUtillityModal.jsx
  src/components/common/DeleteModal/DeleteModal.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/store/function.js
  src/store/index.js
Labels: 🦾enhancement

#41 #35 [create] 회원 정보 수정 API 구현
  src/components/common/Header/HeaderUtilBtn/HeaderUtilBtn.jsx
  src/components/common/MenuListForm/MenuListForm.jsx
  src/components/pages/InputUser.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/UserPageForm/UserPageForm.jsx
  src/components/ui/UserPageForm/UserProfilArea/UserProfilArea.jsx
Labels: 🦾enhancement
