Repository codingBear01/cosmost_fe, pull requests merged in 2022-11, with the labels that each got.

#43 Done: 404, error, 회원탈퇴 페이지 하나로 통일 및 관련 기능 구현
  src/App.js
  src/components/index.js
  src/components/pages/ErrorPage.jsx
  src/components/pages/Messages.jsx
  src/components/pages/NotFoundPage.jsx
  src/components/pages/WithdrawalMessage.jsx
  src/components/pages/index.js
  src/index.css
Labels: 🦾enhancement

#45 [create, update] 회원가입 버그 수정, 검색 API 구현, 이메일 인증 API 구현
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderSearchBar/HeaderSearchBar.jsx
  src/components/common/Header/HeaderUtilBtn/HeaderUtilBtn.jsx
  src/components/common/Input/Input.jsx
  src/components/common/MenuListForm/MenuListForm.jsx
  src/components/pages/InputEmail.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
Labels: 🐛bug, 🦾enhancement

#47 #3 [create] 코스 작성 페이지 버그 수정 및 코스 상세 페이지 대부분의 API 구현
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/UserPageForm/UserPageForm.jsx
  src/store/function.js
  src/store/index.js
Labels: 🐛bug, 🦾enhancement

#48 Done: 코스 좋아요 및 코스 리뷰 좋아요 구현 등
  src/App.js
  src/apis/Auth.js
  src/apis/Board.js
  src/apis/Comment.js
  src/apis/Cosmost.js
  src/apis/Popularity.js
  src/components/index.js
  src/components/pages/DisplayFindedUser.jsx
  src/components/pages/FindingUserPage.jsx
  src/components/pages/index.js
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/CoursesForm/SelectingCategoryArea/SelectingCategoryArea.jsx
  src/components/ui/DisplayFindedIdForm/DisplayFindedIdForm.jsx
  src/components/ui/DisplayFindedIdForm/index.js
  src/components/ui/DisplayFindedIdForm/styled.js
  src/components/ui/DisplayFindedUserForm/index.js
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/InputPasswordForm/InputPasswordForm.jsx
  src/components/ui/InputPasswordForm/styled.js
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/RankersForm/RankersContainer/RankersContainer.jsx
  src/components/ui/index.js
  src/store/functions.js
  src/store/index.js
Labels: 🦾enhancement, 🛠refactoring

#49 #5 코스 평점 평균 기준 정렬 API 일부 구현
  src/components/common/OrderingButton/OrderingButton.jsx
  src/components/common/OrderingModal/OrderingModal.jsx
  src/components/common/OrderingModal/styled.js
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/store/functions.js
  src/store/index.js
Labels: 🦾enhancement

#53 Done: 코스 리뷰 좋아요 구현, 키워드 검색 기능 및 코스 조회용 url 관련 코드 수정
  src/components/common/Header/Header.jsx
  src/components/common/Header/HeaderSearchBar/HeaderSearchBar.jsx
  src/components/common/MenuListForm/MenuListForm.jsx
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/styled.js
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/CoursesForm/SelectingCategoryArea/SelectingCategoryArea.jsx
  src/store/functions.js
Labels: 🛠refactoring

#54 Done: 배포용 api 환경변수로 수정
  src/components/common/DeleteModal/DeleteModal.jsx
  src/components/common/Header/HeaderUtilBtn/HeaderUtilBtn.jsx
  src/components/common/HistoriesForm/HistoriesForm.jsx
  src/components/common/ReportForm/ReportForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/CoursesForm/SelectingCategoryArea/SelectingCategoryArea.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx
  src/store/functions.js
Labels: 🛠refactoring

#56 Done: meta 추가, isLoading recoil state 및 loading 페이지 추가
  public/index.html
  src/components/index.js
  src/components/pages/index.js
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/LoadingForm/LoadingForm.jsx
  src/components/ui/LoadingForm/index.js
  src/components/ui/LoadingForm/styled.js
  src/components/ui/MainSection/MainSection.jsx
  src/components/ui/index.js
  src/store/MainCourses.js
  src/store/index.js
  src/store/recoilStates.js
  src/store/temporaryArray/index.js
Labels: 🦾enhancement, 😀solving bug

#58 Done: 로딩 페이지 생성
  public/assets/images/Google.png
  public/assets/images/KakaoTalk.png
  public/assets/images/Naver.png
  public/assets/images/spinner.gif
  public/index.html
  src/components/pages/Loading.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/LoadingForm/LoadingForm.jsx
  src/components/ui/LoadingForm/styled.js
Labels: 🦾enhancement

#59 Done: merge develop branch with main branch
  public/assets/images/Google.png
  public/assets/images/KakaoTalk.png
  public/assets/images/Naver.png
  public/assets/images/spinner.gif
  public/index.html
  src/components/pages/Loading.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/LoadingForm/LoadingForm.jsx
  src/components/ui/LoadingForm/styled.js
Labels: 🦾enhancement

#60 #5 코스 좋아요 정렬 기본 틀 구현
  src/components/common/OrderingModal/OrderingModal.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/store/functions.js
Labels: 🦾enhancement

#61 #5 [update] 코스 조회 API 버그 수정 및 로그인 시 토큰이 삭제되는 버그 수정
  src/apis/api.js
  src/components/common/Header/HeaderUtilBtn/HeaderUtilBtn.jsx
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
Labels: 🔨fixing bug

#63 #35 [create] 회원 정보 수정 API 구현 및 네이버 로그인 API 일부 구현
  public/index.html
  src/App.js
  src/apis/api.js
  src/components/common/MenuListForm/MenuListForm.jsx
  src/components/pages/FindingUserPage.jsx
  src/components/pages/InputPassword.jsx
  src/components/pages/WithdrawUser.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/DaumAddressApiForm/DaumAddressApiForm.jsx
  src/components/ui/DisplayFindedIdForm/DisplayFindedIdForm.jsx
  src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/InputPasswordForm/InputPasswordForm.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/MainSection/MainSection.jsx
  src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx
Labels: 🦾enhancement

#64 Done: 코스 리뷰, 신고, 팔로우 기능 등
  public/assets/images/spinner.gif
  src/App.js
  src/apis/api.js
  src/apis/index.js
  src/components/common/CourseUtillityModal/CourseUtillityModal.jsx
  src/components/common/CourseUtillityModal/index.js
  src/components/common/CourseUtillityModal/styled.js
  src/components/common/DeleteModal/DeleteModal.jsx
  src/components/common/DeleteModal/index.js
  src/components/common/DeleteModal/styled.js
  src/components/common/Header/HeaderSearchBar/HeaderSearchBar.jsx
  src/components/common/HistoriesForm/HistoriesForm.jsx
  src/components/common/MenuListForm/styled.js
  src/components/common/ReportForm/ReportForm.jsx
  src/components/common/ReportForm/styled.js
  src/components/common/index.js
  src/components/index.js
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseReview/styled.js
  src/components/ui/CourseDetailForm/CourseReviewRegisterForm/CourseReviewRegisterForm.jsx
  src/components/ui/CourseDetailForm/CourseReviewRegisterForm/styled.js
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/styled.js
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/CoursesForm/SelectingCategoryArea/SelectingCategoryArea.jsx
  src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx
  src/components/ui/FollowsForm/FollowListItem/index.js
  src/components/ui/FollowsForm/FollowListItem/styled.js
  src/components/ui/FollowsForm/FollowsForm.jsx
  src/components/ui/FollowsForm/index.js
  src/components/ui/FollowsForm/styled.js
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/LoadingForm/LoadingForm.jsx
  src/components/ui/RankersForm/RankersForm.jsx
  src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx
  src/store/apis.js
  src/store/index.js
  src/store/recoilStates.js
  src/store/temporaryArray/Follows.js
  src/store/temporaryArray/Rankers.js
  src/store/temporaryArray/ReportHistories.js
  src/store/temporaryArray/index.js
Labels: 🦾enhancement, 🔨fixing bug

#65 Done: merge develop branch with main branch
  public/assets/images/spinner.gif
  public/index.html
  src/App.js
  src/apis/api.js
  src/apis/index.js
  src/components/common/CourseUtillityModal/CourseUtillityModal.jsx
  src/components/common/CourseUtillityModal/index.js
  src/components/common/CourseUtillityModal/styled.js
  src/components/common/DeleteModal/DeleteModal.jsx
  src/components/common/DeleteModal/index.js
  src/components/common/DeleteModal/styled.js
  src/components/common/Header/HeaderSearchBar/HeaderSearchBar.jsx
  src/components/common/HistoriesForm/HistoriesForm.jsx
  src/components/common/MenuListForm/MenuListForm.jsx
  src/components/common/MenuListForm/styled.js
  src/components/common/ReportForm/ReportForm.jsx
  src/components/common/ReportForm/styled.js
  src/components/common/index.js
  src/components/index.js
  src/components/pages/FindingUserPage.jsx
  src/components/pages/InputPassword.jsx
  src/components/pages/WithdrawUser.jsx
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseReview/styled.js
  src/components/ui/CourseDetailForm/CourseReviewRegisterForm/CourseReviewRegisterForm.jsx
  src/components/ui/CourseDetailForm/CourseReviewRegisterForm/styled.js
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/styled.js
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/CoursesForm/SelectingCategoryArea/SelectingCategoryArea.jsx
  src/components/ui/DaumAddressApiForm/DaumAddressApiForm.jsx
  src/components/ui/DisplayFindedIdForm/DisplayFindedIdForm.jsx
  src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx
  src/components/ui/FollowsForm/FollowListItem/index.js
  src/components/ui/FollowsForm/FollowListItem/styled.js
  src/components/ui/FollowsForm/FollowsForm.jsx
  src/components/ui/FollowsForm/index.js
  src/components/ui/FollowsForm/styled.js
  src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/InputPasswordForm/InputPasswordForm.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/LoadingForm/LoadingForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/MainSection/MainSection.jsx
  src/components/ui/RankersForm/RankersForm.jsx
  src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx
  src/store/apis.js
  src/store/index.js
  src/store/recoilStates.js
  src/store/temporaryArray/Follows.js
  src/store/temporaryArray/Rankers.js
  src/store/temporaryArray/ReportHistories.js
  src/store/temporaryArray/index.js
Labels: 🦾enhancement

#66 Done: 해시태그 검색 버그 수정, 이미지 업로드 시 확장자 검증, ui 수정 등
  src/App.js
  src/apis/api.js
  src/components/common/Button/Button.jsx
  src/components/common/HistoriesForm/HistoriesForm.jsx
  src/components/common/HistoriesForm/HistoryListItem/HistoryListItem.jsx
  src/components/common/HistoriesForm/HistoryListItem/index.js
  src/components/common/HistoriesForm/HistoryListItem/styled.js
  src/components/common/HistoriesForm/index.js
  src/components/common/HistoriesForm/styled.js
  src/components/common/Icon/styled.js
  src/components/common/OrderingModal/OrderingModal.jsx
  src/components/common/ReportForm/ReportForm.jsx
  src/components/common/SmallProfilePic/styled.js
  src/components/index.js
  src/components/pages/Rankers.jsx
  src/components/pages/index.js
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseReview/styled.js
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/Course/styled.js
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/DisplayFindedIdForm/DisplayFindedIdForm.jsx
  src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx
  src/components/ui/FollowsForm/FollowsForm.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/InputUserForm/styled.js
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/RankersForm/RankerList/RankerList.jsx
  src/components/ui/RankersForm/RankerList/index.js
  src/components/ui/RankersForm/RankerList/styled.js
  src/components/ui/RankersForm/RankersBox/RankersBox.jsx
  src/components/ui/RankersForm/RankersBox/index.js
  src/components/ui/RankersForm/RankersBox/styled.js
  src/components/ui/RankersForm/RankersContainer/RankersContainer.jsx
  src/components/ui/RankersForm/RankersContainer/index.js
  src/components/ui/RankersForm/RankersContainer/styled.js
  src/components/ui/RankersForm/RankersForm.jsx
  src/components/ui/RankersForm/index.js
  src/components/ui/RankersForm/styled.js
  src/components/ui/index.js
Labels: 🛠refactoring, 🔨fixing bug

#67 #35, #6 [create] 네이버 로그인 API, 회원 탈퇴 API 버그 수정
  src/App.js
  src/apis/api.js
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/DaumAddressApiForm/DaumAddressApiForm.jsx
  src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/MainSection/MainSection.jsx
  src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx
Labels: 🦾enhancement, 🔨fixing bug

#69 Done: merge develop branch with main branch
  src/App.js
  src/apis/api.js
  src/components/common/Button/Button.jsx
  src/components/common/HistoriesForm/HistoriesForm.jsx
  src/components/common/HistoriesForm/HistoryListItem/HistoryListItem.jsx
  src/components/common/HistoriesForm/HistoryListItem/index.js
  src/components/common/HistoriesForm/HistoryListItem/styled.js
  src/components/common/HistoriesForm/index.js
  src/components/common/HistoriesForm/styled.js
  src/components/common/Icon/styled.js
  src/components/common/OrderingModal/OrderingModal.jsx
  src/components/common/ReportForm/ReportForm.jsx
  src/components/common/SmallProfilePic/styled.js
  src/components/index.js
  src/components/pages/Rankers.jsx
  src/components/pages/index.js
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseReview/styled.js
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/Course/styled.js
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/DaumAddressApiForm/DaumAddressApiForm.jsx
  src/components/ui/DisplayFindedIdForm/DisplayFindedIdForm.jsx
  src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx
  src/components/ui/FollowsForm/FollowsForm.jsx
  src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/InputUserForm/styled.js
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/MainSection/MainSection.jsx
  src/components/ui/RankersForm/RankerList/RankerList.jsx
  src/components/ui/RankersForm/RankerList/index.js
  src/components/ui/RankersForm/RankerList/styled.js
  src/components/ui/RankersForm/RankersBox/RankersBox.jsx
  src/components/ui/RankersForm/RankersBox/index.js
  src/components/ui/RankersForm/RankersBox/styled.js
  src/components/ui/RankersForm/RankersContainer/RankersContainer.jsx
  src/components/ui/RankersForm/RankersContainer/index.js
  src/components/ui/RankersForm/RankersContainer/styled.js
  src/components/ui/RankersForm/RankersForm.jsx
  src/components/ui/RankersForm/index.js
  src/components/ui/RankersForm/styled.js
  src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx
  src/components/ui/index.js
Labels: 🦾enhancement

#70 #5 코스 검색 버그 전면 수정
  src/components/common/OrderingModal/OrderingModal.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
Labels: 🔨fixing bug

#71 [update] api token 수정
  src/apis/api.js
  src/apis/index.js
  src/components/common/HistoriesForm/HistoriesForm.jsx
  src/components/common/ReportForm/ReportForm.jsx
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseReviewRegisterForm/CourseReviewRegisterForm.jsx
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/DaumAddressApiForm/DaumAddressApiForm.jsx
  src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx
  src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/InputPasswordForm/InputPasswordForm.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx
Labels: 🔨fixing bug

#72 Done: merge develop branch with main branch
  src/apis/api.js
  src/apis/index.js
  src/components/common/HistoriesForm/HistoriesForm.jsx
  src/components/common/OrderingModal/OrderingModal.jsx
  src/components/common/ReportForm/ReportForm.jsx
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseReviewRegisterForm/CourseReviewRegisterForm.jsx
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/DaumAddressApiForm/DaumAddressApiForm.jsx
  src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx
  src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/InputPasswordForm/InputPasswordForm.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx
Labels: 🦾enhancement

#73 #5 [update] 코스 검색 정렬 전환 버그 수정
  src/components/ui/CoursesForm/CoursesForm.jsx
Labels: 🔨fixing bug

#74 Fix: 이메일 입력폼에 네이버 이메일 확인 정규식 추가
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
Labels: 🦾enhancement

#75 Done: sns 공유하기 수정, 코스 관련 정렬 버그 수정
  public/index.html
  src/apis/api.js
  src/apis/index.js
  src/components/common/HistoriesForm/HistoryListItem/HistoryListItem.jsx
  src/components/common/OrderingModal/OrderingModal.jsx
  src/components/common/ReportForm/ReportForm.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseReviewRegisterForm/CourseReviewRegisterForm.jsx
  src/components/ui/CourseDetailForm/CourseSharingModal/CourseSharingModal.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/store/MainCourses.js
  src/store/functions.js
Labels: 🔨fixing bug

#76 Done: 해시태그 검색 수정
  src/components/ui/CoursesForm/CoursesForm.jsx
Labels: 🔨fixing bug

#77 Fix: 코스 상세 조회 시 평균 평점 ui, 아이디 찾기 전체 보여주기 수정
  src/apis/api.js
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/DisplayFindedIdForm/DisplayFindedIdForm.jsx
Labels: 🔨fixing bug

#78 Fix: 팔로우 기능 수정
  src/apis/api.js
  src/apis/index.js
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx
  src/components/ui/FollowsForm/FollowsForm.jsx
  src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx
  src/components/ui/InputPasswordForm/InputPasswordForm.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/UserPageForm/UserPageForm.jsx
  src/components/ui/UserPageForm/UserProfilArea/UserProfilArea.jsx
  src/components/ui/UserPageForm/UserProfilArea/styled.js
Labels: 🦾enhancement, 🔨fixing bug

#79 #3 [update] 코스 상세페이지 네이버 지도 주석 처리 해제
  pull_request_template.md
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/store/functions.js
Labels: 🐛bug

#80 #3 [update] 코스 등록 시 마크 표시되게 수정
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
Labels: 🐛bug

#81 #4 [update] 코스 등록 마커 표시 버그 수정2
  package.json
Labels: 🐛bug

#82 Done: 코스 검색 및 정렬 로직 수정
  src/components/common/Header/HeaderSearchBar/HeaderSearchBar.jsx
  src/components/common/MenuListForm/MenuListForm.jsx
  src/components/common/OrderingModal/OrderingModal.jsx
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/CoursesForm/SelectingCategoryArea/SelectingCategoryArea.jsx
  src/components/ui/MainSection/MainCourse/MainCourse.jsx
  src/components/ui/MainSection/MainSection.jsx
  src/store/MainCourses.js
  src/store/recoilStates.js
Labels: 🔨fixing bug

#83 Done: 코스 검색 및 정렬 ui 수정
  src/components/common/OrderingModal/OrderingModal.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/store/MainCourses.js
Labels: 🦾enhancement, 🔨fixing bug

#84 Done: UI 및 버그 수정
  src/App.js
  src/components/pages/Messages.jsx
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/CourseRegistrationForm/styled.js
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx
  src/components/ui/FollowsForm/FollowsForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/store/functions.js
Labels: 🔨fixing bug

#86 Done: 코스 수정 버그 수정 작업
  src/apis/api.js
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
Labels: 🔨fixing bug

#87 Done: Route token 분기 처리 수정
  src/App.js
  src/components/ui/LoginForm/LoginForm.jsx
Labels: 🔨fixing bug

#88 Done: 코스 상세 조회 네이버 지도 주석 해제, 코스 리뷰 개수 조회 안 되면 0으로 표시
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/store/functions.js
Labels: 🔨fixing bug

#89 Fix: Route 분기 시 token 활용
  src/App.js
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
Labels: 🔨fixing bug

#91 Done: 회원정보 조회 폼 생성
  src/App.js
  src/apis/api.js
  src/components/common/Header/HeaderUtilBtn/HeaderUtilBtn.jsx
  src/components/common/HistoriesForm/HistoriesForm.jsx
  src/components/common/Icon/styled.js
  src/components/common/Input/styled.js
  src/components/common/MenuListForm/MenuListForm.jsx
  src/components/common/OrderingModal/OrderingModal.jsx
  src/components/common/UtilTitle/UtilTitle.jsx
  src/components/index.js
  src/components/pages/UserInformation.jsx
  src/components/pages/index.js
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx
  src/components/ui/CourseDetailForm/CourseTitleAndDate/CourseTitleAndDate.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/Course/styled.js
  src/components/ui/CoursesForm/SelectingCategoryArea/SelectingCategoryArea.jsx
  src/components/ui/DaumAddressApiForm/DaumAddressApiForm.jsx
  src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/MainSection/MainSection.jsx
  src/components/ui/UserInformationForm/UserInformationForm.jsx
  src/components/ui/UserInformationForm/index.js
  src/components/ui/UserInformationForm/styled.js
  src/components/ui/UserPageForm/UserProfilArea/UserProfilArea.jsx
  src/components/ui/UserPageForm/UserProfilArea/styled.js
  src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx
  src/components/ui/index.js
  src/store/functions.js
  src/store/index.js
  src/store/recoilStates.js
Labels: 🦾enhancement, 🔨fixing bug

#92 [update] 로그인 토큰 관리 및 정보 수정된 닉네임 반영 버그 수정
  src/App.js
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/UserPageForm/UserPageForm.jsx
Labels: 🔨fixing bug

#93 Fix: 이메일 관련 기능 수정
  src/App.js
  src/apis/api.js
  src/apis/index.js
  src/components/common/Header/HeaderUtilBtn/HeaderUtilBtn.jsx
  src/components/common/MenuListForm/MenuListForm.jsx
  src/components/common/PageContainer/PageContainer.jsx
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx
  src/components/ui/FollowsForm/FollowsForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/UserInformationForm/UserInformationForm.jsx
  src/components/ui/UserPageForm/UserPageForm.jsx
  src/components/ui/UserPageForm/UserProfilArea/UserProfilArea.jsx
  src/store/index.js
  src/store/recoilStates.js
Labels: 🔨fixing bug

#94 Fix: 코스 순서 관련 ui 수정
  src/apis/api.js
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseContentWrap/styled.js
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/Course/styled.js
  src/components/ui/CoursesForm/CoursesForm.jsx
Labels: 🔨fixing bug

#95 Fix: 장소 한줄평 스타일 수정
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
Labels: 🔨fixing bug

#96 [update] 이메일 변경 버그 수정
  src/components/ui/InputEmailForm/InputEmailForm.jsx
Labels: 🔨fixing bug

#97 [update] 회원 관련 버그 수정
  src/apis/api.js
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/UserPageForm/UserProfilArea/UserProfilArea.jsx
Labels: 🔨fixing bug

#99 Fix: 아이디 및 비밀번호 찾기 버그 수정
  src/apis/api.js
  src/components/pages/FindingUserPage.jsx
  src/components/ui/DisplayFindedIdForm/DisplayFindedIdForm.jsx
  src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx
  src/components/ui/FollowsForm/FollowListItem/styled.js
  src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/InputPasswordForm/InputPasswordForm.jsx
Labels: 🔨fixing bug

#100 [update] 주소 변경 이슈 해결
  src/apis/api.js
  src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
Labels: 🔨fixing bug

#101 Done: toast error를 warn으로 수정
  src/components/common/ReportForm/ReportForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CourseDetailForm/CourseReviewRegisterForm/CourseReviewRegisterForm.jsx
  src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/InputPasswordForm/InputPasswordForm.jsx
  src/components/ui/InputUserForm/InputUserForm.jsx
  src/components/ui/LoginForm/LoginForm.jsx
  src/components/ui/WithdrawUserForm/WithdrawUserForm.jsx
Labels: 🛠refactoring

#102 Done: 코스 순서 UI 및 네이버 마커 UI 수정
  src/apis/api.js
  src/apis/index.js
  src/components/common/ReportForm/ReportForm.jsx
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
  src/components/ui/CourseDetailForm/CourseReview/CourseReview.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/Course/styled.js
  src/components/ui/CoursesForm/SelectingCategoryArea/SelectingCategoryArea.jsx
  src/components/ui/FollowsForm/FollowListItem/FollowListItem.jsx
Labels: 🛠refactoring

#103 Done: 코스 조회 ui 수정
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/Course/styled.js
Labels: 🛠refactoring

#104 [update] 회원가입 이메일 분기 처리 완료
  src/components/ui/InputDetailAddressForm/InputDetailAddressForm.jsx
Labels: 🔨fixing bug

#105 Done: 코스 등록 인풋 폰트 사이즈 수정, 코스 제목 글자수 수정, 마이페이지 메뉴 navigate 분기 처리
  src/components/common/PageContainer/PageContainer.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/components/ui/CourseRegistrationForm/styled.js
  src/components/ui/CoursesForm/Course/Course.jsx
Labels: 🛠refactoring, 🔨fixing bug

#106 Done: 내가 남긴 리뷰 조회에서 코스 제목 조회
  src/apis/api.js
  src/components/common/HistoriesForm/HistoryListItem/HistoryListItem.jsx
Labels: 🔨fixing bug

#107 Done: 코스 제목 글자 수 스타일 수정
  src/components/ui/CoursesForm/Course/Course.jsx
Labels: 🛠refactoring

#108 Done: 내가 작성한 코스 및 좋아요 한 코스 분기 처리
  src/App.js
  src/components/ui/CoursesForm/CoursesForm.jsx
Labels: 🦾enhancement, 🛠refactoring

#109 Done: 마이 페이지 코스 조회 분기 처리 수정
  src/components/ui/CoursesForm/CoursesForm.jsx
Labels: 🛠refactoring

#110 Done: placeOrder 숫자 삭제
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CoursesForm/Course/Course.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
Labels: 🛠refactoring

#111 Done: 해시태그 및 키워드 검색 결과 메시지 수정
  src/components/ui/CoursesForm/CoursesForm.jsx
Labels: 🛠refactoring, 🔨fixing bug

#112 Done: api 분리 리팩토링
  src/apis/api.js
  src/apis/index.js
  src/components/common/Header/HeaderUtilBtn/HeaderUtilBtn.jsx
  src/components/ui/CourseDetailForm/CourseContentWrap/CourseContentWrap.jsx
  src/components/ui/CourseDetailForm/CourseReviewRegisterForm/CourseReviewRegisterForm.jsx
  src/components/ui/CoursesForm/CoursesForm.jsx
  src/components/ui/InputEmailForm/InputEmailForm.jsx
  src/components/ui/UserPageForm/UserPageForm.jsx
Labels: 🛠refactoring

#113 Done: imgUrl 수정
  src/components/ui/CourseDetailForm/CourseImageCarousel/CourseImageCarousel.jsx
  src/components/ui/CourseRegistrationForm/CourseRegistrationForm.jsx
  src/store/functions.js
Labels: 🛠refactoring, 🔨fixing bug

#114 Done: url 복사 수정
  src/components/ui/CourseDetailForm/CourseSharingAndLikeButton/CourseSharingAndLikeButton.jsx
Labels: 🔨fixing bug

#115 Done: 네이버 지도 마커 ui 수정
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
Labels: 🛠refactoring

#116 Done: 상세 조회 코스 마커 ui 수정
  src/components/ui/CourseDetailForm/CourseDetailForm.jsx
Labels: 🛠refactoring
